### ISSUE TITLE
[功能建议]: 希望文档里加入微博使用说明

### ISSUE THREAD

**Issue by devil233-ui** [zhiyu1998/rconsole-plugin#19]
### 你的功能建议是否和某个问题相关？

帮助菜单里有此功能，但bot对任意微博链接输出结果均为`解析失败：无法获取到wb的id`，但是文档里没有相关说明，锅巴里也没地方配置

### 你希望看到什么解决方案？

在文档加入相关说明并于锅巴加入配置

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by zhiyu1998** [comment]
前几天刚 weibo 刚升级，我也跟着升级，所以你升级下试试

另外 '解析失败：无法获取到wb的id' ，就是没有数据，识别不到
